package com.spider.search.mapper;

import com.spider.search.vo.Search;

import java.util.List;

public interface SearchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Search
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Search
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    int insert(Search record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Search
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    Search selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Search
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    List<Search> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Search
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    int updateByPrimaryKey(Search record);
}