package com.spider.search.mapper;

import com.spider.search.vo.SearchItem;
import java.util.List;

public interface SearchItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    int insert(SearchItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    SearchItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    List<SearchItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    int updateByPrimaryKey(SearchItem record);
}