package com.spider.search.mapper;

import com.spider.search.vo.SearchSite;
import java.util.List;

public interface SearchSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 09:55:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 09:55:20 CST 2018
     */
    int insert(SearchSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 09:55:20 CST 2018
     */
    SearchSite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 09:55:20 CST 2018
     */
    List<SearchSite> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 09:55:20 CST 2018
     */
    int updateByPrimaryKey(SearchSite record);
}