package com.ibeetl.admin.core.mapper;

import com.ibeetl.admin.core.web.vo.SearchItem;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SearchItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:38:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:38:11 CST 2018
     */
    int insert(SearchItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:38:11 CST 2018
     */
    SearchItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:38:11 CST 2018
     */
    @Select("SELECT * FROM search_item")
    List<SearchItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:38:11 CST 2018
     */
    int updateByPrimaryKey(SearchItem record);

    @Select("SELECT * FROM search_item WHERE site_id = #{siteId}")
    List<SearchItem> findBySiteId(Integer siteId);

}