package com.ibeetl.admin.core.mapper;

import com.ibeetl.admin.core.web.vo.SearchSite;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SearchSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    int insert(SearchSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    SearchSite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    List<SearchSite> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    int updateByPrimaryKey(SearchSite record);

    @Select("SELECT * FROM search_site WHERE website = #{website}")
    List<SearchSite> findbyWebsite(String website);

    @Select({"<script>"
            ,"SELECT * FROM search_site"
            ,"<where> 1=1"
            ,"<if test='website!=null'>"
            , "and website=#{website}"
            , "</if>"
            ,"</where>"
            ,"imit #{start,jdbcType=INTEGER},#{size,jdbcType=INTEGER}"
            ,"</script>"})
    List<SearchSite> findPageList(String website,Integer start,Integer size);
}