package com.spider.search.vo;

import java.io.Serializable;

public class Search implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Search.id
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Search.website
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Search.domain
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Search.method
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Search.url
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Search.keywords
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Search
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Search.id
     *
     * @return the value of Search.id
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Search.id
     *
     * @param id the value for Search.id
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Search.website
     *
     * @return the value of Search.website
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Search.website
     *
     * @param website the value for Search.website
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Search.domain
     *
     * @return the value of Search.domain
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Search.domain
     *
     * @param domain the value for Search.domain
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Search.method
     *
     * @return the value of Search.method
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Search.method
     *
     * @param method the value for Search.method
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Search.url
     *
     * @return the value of Search.url
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Search.url
     *
     * @param url the value for Search.url
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Search.keywords
     *
     * @return the value of Search.keywords
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Search.keywords
     *
     * @param keywords the value for Search.keywords
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Search
     *
     * @mbg.generated Tue Nov 20 17:33:13 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", website=").append(website);
        sb.append(", domain=").append(domain);
        sb.append(", method=").append(method);
        sb.append(", url=").append(url);
        sb.append(", keywords=").append(keywords);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}