package com.spider.search.vo;

import java.io.Serializable;
import java.util.Date;

public class SearchItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.id
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.site_id
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private Integer siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.base_uri
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String baseUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.book_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String bookItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.book_picture
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String bookPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.book_name
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.book_author
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.book_intro
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String bookIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.book_update
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String bookUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.book_words
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private String bookWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.update_time
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_item.create_time
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.id
     *
     * @return the value of search_item.id
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.id
     *
     * @param id the value for search_item.id
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.site_id
     *
     * @return the value of search_item.site_id
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public Integer getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.site_id
     *
     * @param siteId the value for search_item.site_id
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setSiteId(Integer siteId) {
        this.siteId = siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.base_uri
     *
     * @return the value of search_item.base_uri
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBaseUri() {
        return baseUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.base_uri
     *
     * @param baseUri the value for search_item.base_uri
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBaseUri(String baseUri) {
        this.baseUri = baseUri == null ? null : baseUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.book_item
     *
     * @return the value of search_item.book_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBookItem() {
        return bookItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.book_item
     *
     * @param bookItem the value for search_item.book_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBookItem(String bookItem) {
        this.bookItem = bookItem == null ? null : bookItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.book_picture
     *
     * @return the value of search_item.book_picture
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBookPicture() {
        return bookPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.book_picture
     *
     * @param bookPicture the value for search_item.book_picture
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBookPicture(String bookPicture) {
        this.bookPicture = bookPicture == null ? null : bookPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.book_name
     *
     * @return the value of search_item.book_name
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.book_name
     *
     * @param bookName the value for search_item.book_name
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.book_author
     *
     * @return the value of search_item.book_author
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.book_author
     *
     * @param bookAuthor the value for search_item.book_author
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.book_intro
     *
     * @return the value of search_item.book_intro
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBookIntro() {
        return bookIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.book_intro
     *
     * @param bookIntro the value for search_item.book_intro
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBookIntro(String bookIntro) {
        this.bookIntro = bookIntro == null ? null : bookIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.book_update
     *
     * @return the value of search_item.book_update
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBookUpdate() {
        return bookUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.book_update
     *
     * @param bookUpdate the value for search_item.book_update
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBookUpdate(String bookUpdate) {
        this.bookUpdate = bookUpdate == null ? null : bookUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.book_words
     *
     * @return the value of search_item.book_words
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public String getBookWords() {
        return bookWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.book_words
     *
     * @param bookWords the value for search_item.book_words
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setBookWords(String bookWords) {
        this.bookWords = bookWords == null ? null : bookWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.update_time
     *
     * @return the value of search_item.update_time
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.update_time
     *
     * @param updateTime the value for search_item.update_time
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_item.create_time
     *
     * @return the value of search_item.create_time
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_item.create_time
     *
     * @param createTime the value for search_item.create_time
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_item
     *
     * @mbg.generated Wed Nov 21 13:21:48 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", siteId=").append(siteId);
        sb.append(", baseUri=").append(baseUri);
        sb.append(", bookItem=").append(bookItem);
        sb.append(", bookPicture=").append(bookPicture);
        sb.append(", bookName=").append(bookName);
        sb.append(", bookAuthor=").append(bookAuthor);
        sb.append(", bookIntro=").append(bookIntro);
        sb.append(", bookUpdate=").append(bookUpdate);
        sb.append(", bookWords=").append(bookWords);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}