package com.spider.search.vo;

import java.io.Serializable;
import java.util.Date;

public class SearchSite implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.id
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.website
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.domain
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.method
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.url
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.keywords
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.create_time
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.update_time
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.pageSize
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private String pagesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_site.pageNum
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private String pagenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.id
     *
     * @return the value of search_site.id
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.id
     *
     * @param id the value for search_site.id
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.website
     *
     * @return the value of search_site.website
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.website
     *
     * @param website the value for search_site.website
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.domain
     *
     * @return the value of search_site.domain
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.domain
     *
     * @param domain the value for search_site.domain
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.method
     *
     * @return the value of search_site.method
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.method
     *
     * @param method the value for search_site.method
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.url
     *
     * @return the value of search_site.url
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.url
     *
     * @param url the value for search_site.url
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.keywords
     *
     * @return the value of search_site.keywords
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.keywords
     *
     * @param keywords the value for search_site.keywords
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.create_time
     *
     * @return the value of search_site.create_time
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.create_time
     *
     * @param createTime the value for search_site.create_time
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.update_time
     *
     * @return the value of search_site.update_time
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.update_time
     *
     * @param updateTime the value for search_site.update_time
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.pageSize
     *
     * @return the value of search_site.pageSize
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public String getPagesize() {
        return pagesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.pageSize
     *
     * @param pagesize the value for search_site.pageSize
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setPagesize(String pagesize) {
        this.pagesize = pagesize == null ? null : pagesize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_site.pageNum
     *
     * @return the value of search_site.pageNum
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public String getPagenum() {
        return pagenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_site.pageNum
     *
     * @param pagenum the value for search_site.pageNum
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    public void setPagenum(String pagenum) {
        this.pagenum = pagenum == null ? null : pagenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_site
     *
     * @mbg.generated Wed Nov 21 16:01:33 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", website=").append(website);
        sb.append(", domain=").append(domain);
        sb.append(", method=").append(method);
        sb.append(", url=").append(url);
        sb.append(", keywords=").append(keywords);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", pagesize=").append(pagesize);
        sb.append(", pagenum=").append(pagenum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}